version: "3"

services:
  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    external: true
