version: "3"

x-logging:
  &tag-json-logs
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - homelab
    logging: *tag-json-logs

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    networks:
      - homelab
    logging: *tag-json-logs

  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.1
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /homelab/config/promtail.yml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - homelab
    logging: *tag-json-logs

networks:
  homelab:
    name: homelab
    external: true