version: "3"

x-logging:
  &tag-json-logs
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.10.0 # Change to portainer/portainer-ce if you do not have a license.
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.erhbg.com`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - homelab
    logging: *tag-json-logs

networks:
  homelab:
    name: homelab
