version: "3"

x-logging:
  &tag-json-logs
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  valheim:
    container_name: valheim
    image: lloesche/valheim-server
    restart: unless-stopped
    cap_add:
      - sys_nice
    environment:
      - SERVER_NAME=${VALHEIM_WORLD_NAME}
      - WORLD_NAME=${VALHEIM_WORLD_NAME}
      - SERVER_PASS=${VALHEIM_SERVER_PASSWORD}
      - SERVER_PUBLIC=false
    ports:
      - 2456-2457:2456-2457/udp
    volumes:
      - valheim-data:/opt/valheim
      - valheim-config:/config
    networks:
      - homelab
    logging: *tag-json-logs

networks:
  homelab:
    name: homelab
    external: true

volumes:
  valheim-data:
    name: valheim-data