entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/default.cert"
        keyFile: "/etc/traefik/certs/default.key"

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: false
  insecure: false

log:
  level: DEBUG

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

  file:
    filename: /etc/traefik/traefik.yml
    watch: true
    