version: "3"

x-logging:
  &tag-json-logs
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:2.11.0
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - homelab
    logging: *tag-json-logs

networks:
  homelab:
    name: homelab
