global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'docker01.erhbg.com'
    scrape_interval: 10s 
    static_configs:
      - targets:
        - cadvisor:8080
        - node-exporter:9100
        - localhost:9090

  - job_name: 'opn.erhbg.com'
    scrape_interval: 10s
    static_configs:
      - targets:
        - opn.erhbg.com:9100
